# Jekyll config for GitHub Pages
title: My Site
description: Splash + Markdown Logbook with Pagination
baseurl: "" # do not change for user/organization site repos; for project pages you may set it to "/REPO"
url: ""

# Use GitHub Pages-compatible theme (optional). We'll override with our own layout and CSS.
theme: minima

# Pagination
paginate: 5
paginate_path: "/logbook/page:num"

# Plugins supported by GitHub Pages (jekyll-paginate is supported)
plugins:
  - jekyll-paginate

collections:
  writing:
    output: true
    permalink: /writing/:name/

defaults:
  - scope:
      path: ""
      type: writing
    values:
      layout: post  # or "writing" if you make a custom layout

# If your theme supports header_pages (e.g., minima):
header_pages:
  - logbook.md
  - projects.md
  - writing.md